APP.mobData = function($scope){
	$scope.mobData = [
	{
		id: 1,
		imgsrc: "img/mob1.png",
		x: 0,
		y: 0,
		xspeed: 2,
		yspeed: 0,
		damage: 25,
		maxHealth: 15,
		currentHealth: 15,
		defense: 0,
		targetRange: 0,
		target: null,
		box: $scope.createBox(40, 40, 40, 10),	
		zig: null,
		score: 2,
		deadTimer: 70,
	},
	{
		id: 2,
		imgsrc: "img/mob2.png",
		x: 0,
		y: 0,
		xspeed: 4,
		yspeed: 2,
		damage: 40,
		maxHealth: 20,
		currentHealth: 20,
		defense: 0,
		targetRange: 800,
		target: null,
		box: $scope.createBox(80, 50, 30, 10),	
		zig: null,
		score: 2,
		deadTimer: 70,
	},
	{
		id: 3,
		imgsrc: "img/mob3.png",
		x: 0,
		y: 0,
		xspeed: 5,
		yspeed: 2,
		damage: 60,
		maxHealth: 10,
		currentHealth: 10,
		defense: 0,
		targetRange: 0,
		target: null,
		box: $scope.createBox(70, 50, 10, 10),
		zig: {
			zigUp: false,
			zigDown: false,
			zigDestY: 0,
			zigFactor: 250,
		},	
		score: 1,
		deadTimer: 70,
	},
	{
		id: 4,
		imgsrc: "img/mob4.png",
		x: 0,
		y: 0,
		xspeed: 7,
		yspeed: 0,
		damage: 75,
		maxHealth: 25,
		currentHealth: 25,
		defense: 0,
		targetRange: 0,
		target: null,
		box: $scope.createBox(100, 70, 10, 20),	
		zig: null,
		score: 3,
		deadTimer: 70,
	},
	{
		id: 5,
		imgsrc: "img/mob5.png",
		x: 0,
		y: 0,
		xspeed: 2,
		yspeed: 1,
		damage: 390,
		maxHealth: 100,
		currentHealth: 100,
		defense: 0,
		targetRange: 0,
		target: null,
		box: $scope.createBox(120, 100, 20, 20),	
		zig: null,
		score: 10,
		deadTimer: 70,
	},
	{
		id: 6,
		imgsrc: "img/mob6.png",
		x: 0,
		y: 0,
		xspeed: 3,
		yspeed: 0,
		damage: 70,
		maxHealth: 60,
		currentHealth: 60,
		defense: 0,
		targetRange: 0,
		target: null,
		box: $scope.createBox(80, 70, 20, 10),	
		zig: null,
		score: 5,
		deadTimer: 70,
	},
	];

}