APP.skinData = function($scope){
	$scope.skinData = [
	{
		id: 1,
		name: "Trashy",
		imgsrc: "img/player1.png",
		speed_x: 4,
		speed_y: 4,
		ox: 70,
		oy: 20,
		manaCost: 40,
		manaRegen: 1,
		defense: 10,
		fireRate: 25,
		boxX: 115,
		boxY: 90,
		boxOffsetX: 0,
		boxOffsetY: 0,
		bulletDamage: 10,
		bulletSpeed: 7,
	},
	{
		id: 2,
		name: "Puffer",
		imgsrc: "img/player2.png",
		speed_x: 2,
		speed_y: 3,
		ox: 105,
		oy: 40,
		manaCost: 100,
		manaRegen: 1.5,
		defense: 30,
		fireRate: 40,
		boxX: 135,
		boxY: 100,
		boxOffsetX: 0,
		boxOffsetY: 0,
		bulletDamage: 25,
		bulletSpeed: 6,
	},
	{
		id: 3,
		name: "Flammy",
		imgsrc: "img/player3.png",
		speed_x: 5,
		speed_y: 4,
		ox: 105,
		oy: 40,
		manaCost: 60,
		manaRegen: 1.25,
		defense: 10,
		fireRate: 25,
		boxX: 135,
		boxY: 100,
		boxOffsetX: 0,
		boxOffsetY: 0,
		bulletDamage: 15,
		bulletSpeed: 8,
	},
	{
		id: 4,
		name: "Lightning",
		imgsrc: "img/player4.png",
		speed_x: 6,
		speed_y: 4,
		ox: 80,
		oy: 30,
		manaCost: 50,
		manaRegen: 2,
		defense: 0,
		fireRate: 15,
		boxX: 130,
		boxY: 90,
		boxOffsetX: 0,
		boxOffsetY: 0,
		bulletDamage: 10,
		bulletSpeed: 10,
	},
	]
}