APP.skinData = function($scope){
	$scope.skinData = [
	{
		id: 1,
		name: "Trashy",
		imgsrc: "img/player1.png",
		speed_x: 4,
		speed_y: 4,
		ox: 88,
		oy: 42,
		manaCost: 40,
		manaRegen: 1,
		defense: 10,
		fireRate: 25,
		boxX: 80,
		boxY: 80,
		boxOffsetX: 10,
		boxOffsetY: 5,
		bulletDamage: 10,
		bulletSpeed: 7,
	},
	{
		id: 2,
		name: "Puffer",
		imgsrc: "img/player2.png",
		speed_x: 2,
		speed_y: 3,
		ox: 102,
		oy: 60,
		manaCost: 100,
		manaRegen: 1.5,
		defense: 30,
		fireRate: 40,
		boxX: 90,
		boxY: 90,
		boxOffsetX: 20,
		boxOffsetY: 5,
		bulletDamage: 25,
		bulletSpeed: 6,
	},
	{
		id: 3,
		name: "Flammy",
		imgsrc: "img/player3.png",
		speed_x: 5,
		speed_y: 4,
		ox: 98,
		oy: 55,
		manaCost: 60,
		manaRegen: 1.25,
		defense: 10,
		fireRate: 25,
		boxX: 96,
		boxY: 87,
		boxOffsetX: 10,
		boxOffsetY: 5,
		bulletDamage: 15,
		bulletSpeed: 8,
	},
	{
		id: 4,
		name: "Lightning",
		imgsrc: "img/player4.png",
		speed_x: 6,
		speed_y: 4,
		ox: 100,
		oy: 42,
		manaCost: 45,
		manaRegen: 1.75,
		defense: 0,
		fireRate: 12,
		boxX: 94,
		boxY: 77,
		boxOffsetX: 12,
		boxOffsetY: 10,
		bulletDamage: 10,
		bulletSpeed: 10,
	},
	]
}